#!/bin/sh

### BEGIN INIT INFO
# Provides:          jsonbot
# Required-Start:    $local_fs $remote_fs $network $named
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: JSONBOT 
# Description:       The JSON everywhere bot!
### END INIT INFO

NAME=jsb-fleet
DESC="JSONBOT"
DATADIR=/var/lib/jsonbot
PIDFILE=/var/run/jsonbot.pid
LOGFILE=/var/log/jsonbot.log

PID=`cat $PIDFILE` 2>/dev/null

# Include gozerbot defaults if available
if [ -f /etc/default/jsonbot ] ; then
    . /etc/default/jsonbot
fi

if [ "$RUN" != "yes" ] ; then
    echo "$NAME disabled; edit /etc/default/jsonbot"
    exit 0
fi

if [ -n "$RUNUSER" ] ; then
    RUNUSER=jsonbot
fi

status()
{
	test -n "$PID" && ps auxw | grep -v grep | grep jsonbot | grep -q -s " $PID " && return 0
        return 1
}

stop()
{
	if status
	then
		kill -KILL $PID
	fi
}

start()
{
	status && exit 1 # already running
        if [ -f "/etc/jsonbot/config" ]		
        then
        	su $RUNUSER -c "$NAME -d $DATADIR $ARGSTRING 2>&1 1>/dev/null &"
	else
                jsb-init -d $DATADIR
        	rm -rf /etc/jsonbot/config
		ln -s /var/lib/jsonbot/config /etc/jsonbot/config
		su $RUNUSER -c "$NAME -d $DATADIR $ARGSTRING 2>&1 1>/dev/null &"
	fi
}

case "$1" in
start)
	echo -n "Starting $DESC: $NAME"
	start
	case "$?" in
		0) echo "." ; exit 0 ;;
		1) echo " (already running)." ; exit 0 ;;
		*) echo " (failed)." ; exit 1 ;;
	esac
	;;
stop)
	echo -n "Stopping $DESC: $NAME"
	stop
	case "$?" in
		0) echo "." ; exit 0 ;;
		1) echo " (not running)." ; exit 0 ;;
		*) echo " (failed)." ; exit 1 ;;
	esac
	;;
restart|force-reload|reload)
	echo -n "Restarting $DESC: $NAME"
	stop
	start
	;;
status)
	echo -n "Status of $DESC service: "
	status
	case "$?" in
		0) echo "running." ; exit 0 ;;
		1) echo "not running." ; exit 3 ;;
	esac
	;;
*)
	echo "Usage: /etc/init.d/jsonbot {start|stop|reload|force-reload|restart|status}" >&2
	exit 1
	;;
esac

*t
